### ISSUE TITLE
puppetforge relase are missing latest PR

### ISSUE THREAD

**Issue by ehedgren** [scrat14/puppet-ovirt_guest_agent#2]
Seems as this [PR](https://github.com/scrat14/puppet-ovirt_guest_agent/pull/1) are missing from the release on https://forge.puppet.com/.

Would you mind releasing the latest ?

**Comment by scrat14** [comment]
There will be a new release this week including this patch.

**Comment by scrat14** [comment]
new release is uploaded to puppet forge, including support for RHEV hypervisors (in addition to oVirt nodes)
