### ISSUE TITLE
Broken packages can cause service to fail

### ISSUE THREAD

**Issue by nvtkaszpir** [scrat14/puppet-ovirt_guest_agent#4]
Found the issue on CentOS 7.3 today. Providing an info if someone has similar problem. Maybe this could be added to README... but not really sure.

When installing ovirt-guest-agent-common all in theory works well, but service will be in failed status.
Puppet will show service started successfully, but any extra provisions will ensure service is running - so it means service dies after a while after start.
Investigating ovirt-guest-agent logs  shows `Permission Denied` error while accessing virtio-ports.

The problem is that symlink target of `/dev/virtio-ports/com.redhat.rhevm.vdsm`  does not have proper ownership set. Running `udevadm trigger` is not providing repeatable consistent solution.

Workaround: 
Install different package version or force puppet to fix permissions after package install, but before service start.

```puppet
    include ::ovirt_guest_agent

    # fix broken packages due to not triggered udedavm, this is Centos 7.3 specific, probably
    file { '/dev/virtio-ports/com.redhat.rhevm.vdsm':
      links   => 'follow',
      owner   => 'ovirtagent',
      group   => 'ovirtagent',
      before  => Service[$::ovirt_guest_agent::service_name],
      notify  => Service[$::ovirt_guest_agent::service_name],
      require => Package[$::ovirt_guest_agent::package_name],
    }
```

The issue should be fixed by package maintainers for given distro. AFAIR ther's errata for this on RedHat.

**Comment by scrat14** [comment]
Thanks for the information.
Sadly I can't reproduce this error. Neither old CentOS 7.3 installations with ovirt-guest-agent 1.0.12 nor a brand new with lateste patches and ovirt-guest-agent 1.0.13 put's the service into failed state.
I have these permissions after installing guest agent with puppet:
```
# ll /dev/virtio-ports/com.redhat.rhevm.vdsm
lrwxrwxrwx. 1 root root 11 Mar 20 12:03 /dev/virtio-ports/com.redhat.rhevm.vdsm -> ../vport2p1
# ll /dev/vport2p1 
crw-rw----. 1 ovirtagent ovirtagent 248, 1 Mar 20 12:03 /dev/vport2p1
```
Can't see an error in /var/log/messages nor a failed state of ovirt-guest-agent service on CentOS 7.3. Is this issue somehow reproducible?

**Comment by nvtkaszpir** [comment]
Yeah just checked, still exists:

```text
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core


ovirt-guest-agent-common.noarch      1.0.13-2.el7                    @epel

ll /dev/virtio-ports/com.redhat.rhevm.vdsm
lrwxrwxrwx. 1 root root 11 03-24 17:39 /dev/virtio-ports/com.redhat.rhevm.vdsm -> ../vport2p1

ll /dev/vport2p1
crw-------. 1 root root 244, 1 03-24 17:39 /dev/vport2p1

```

**Comment by scrat14** [comment]
Thanks for confirmation. I'll update README in case someone else runs into this problem.
